### ISSUE TITLE
tkinter and cvbridge install

### ISSUE THREAD

**Issue by diptodip** [gtagency/buzzmobile#129] opened 2016-11-12 22:26 UTC
Need to add cv-bridge and tkinter to install script.

**Comment by irapha** [comment] 2016-11-13 03:46
I added `python-tk` in the install script in the `garage-test` branch already. cv bridge should come installed with the rospy packages, no? I thought it was working before.

question: is this a duplicate of #126 ?

**Closed as completed** 2016-11-23 00:30 UTC
Labels: bug
